// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHW3yyGtbAgjboo5zFD3Er2Wfv1F3i5FQ',
    appId: '1:336632968343:android:3dbc313e69a52f3d7325d2',
    messagingSenderId: '336632968343',
    projectId: 'berdua-dev',
    storageBucket: 'berdua-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACEdK4oyqcx6-afqV5UkLYt6K8NePoQyA',
    appId: '1:336632968343:ios:4c1ea1e6c714d4a47325d2',
    messagingSenderId: '336632968343',
    projectId: 'berdua-dev',
    storageBucket: 'berdua-dev.firebasestorage.app',
    iosClientId: '336632968343-5g4r7eciv75361icrqgvom4qc7s9re1h.apps.googleusercontent.com',
    iosBundleId: 'com.berdua.berdua',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQDJmMnGQSgL8Wrx86ZGaDs3K_ure6y8g',
    appId: '1:336632968343:web:79bf02df0ba439287325d2',
    messagingSenderId: '336632968343',
    projectId: 'berdua-dev',
    authDomain: 'berdua-dev.firebaseapp.com',
    storageBucket: 'berdua-dev.firebasestorage.app',
  );

}